# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

include:  ['_data']

# Setup
title:            Sarthak Ahuja
tagline:          'Personal Website'
description:      'Personal Website'
url:              http://sarthakahuja.org
baseurl:          /

author:
  name:           'Sarthak Ahuja'
  url:            https://sarthakahuja.org

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/jokereactive/jokereactive.github.io
