# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

include:  ['_pages']


collections:
  projects:
    output: true
    permalink: /projects/:path/
  work:
    output: true
    permalink: /work/:path/
  experience:
    output: true
    permalink: /experience/:path/
  education:
    output: true
    permalink: /education/:path/
  misc:
    output: true
    permalink: /misc/:path/
relative_permalinks: false

excerpt_separator: "{{ more }}"

# Setup
title:            Sarthak Ahuja
tagline:          'Personal Website'
description:      'If you change the way you look at things, the things you look at change.'
url:              http://sarthakahuja.org
baseurl:          /
imagesurl:		  /assets/images
logosurl:		  /assets/images/logos
headersurl:		  /assets/images/headers
projectimagesurl: /assets/images/projectimages
iconsurl: 		  /assets/images/icons
docsurl: 		  /public/docs
twitter:		  https://twitter.com/srthkhj
facebook:		  https://www.facebook.com/sarthak.ahuja.9
linkedin:		  https://in.linkedin.com/in/sarthakahuja
google:			  https://plus.google.com/u/0/+SarthakAhuja9/posts
mail:			  sarthak12088@iiitd.ac.in

author:
  name:           'Sarthak Ahuja'
  url:            https://sarthakahuja.org

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/FrozenInk/soberCV
  site:			  https://frozenink.github.io
