# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

include:  ['_pages']


collections:
  projects:
    output: true
    permalink: /projects/:path/
  work:
    output: true
    permalink: /work/:path/
  certificate:
    output: true
    permalink: /certificate/:path/
  administrative:
    output: true
    permalink: /administrative/:path/
  education:
    output: true
    permalink: /education/:path/
  misc:
    output: true
    permalink: /misc/:path/
  teaching:
    output: true
    permalink: /teaching/:path/
  publication:
    output: true
    permalink: /publication/:path/
  patent:
    output: true
    permalink: /patent/:path/
  volunteer:
    output: true
    permalink: /volunteer/:path/
relative_permalinks: false

excerpt_separator: "{{ more }}"

# Setup
title:            Sarthak Ahuja
tagline:          'Personal Website'
description:      'If you change the way you look at things, the things you look at change.'
url:              http://sarthakahuja.org
baseurl:          http://sarthakahuja.org/
imagesurl:		  /assets/images
logosurl:		  /assets/images/logos
headersurl:		  /assets/images/headers
projectimagesurl: /assets/images/projectimages
iconsurl: 		  /assets/images/icons
paperthumbnails: /assets/images/paperthumbnails
projectthumbnails: /assets/images/projectthumbnails
patentthumbnails: /assets/images/patentthumbnails
docsurl: 		  /public/docs
behance:      https://www.behance.net/thecoldviews
twitter:		  https://twitter.com/thecoldviews
facebook:		  https://www.facebook.com/sarthak.ahuja.9
linkedin:		  https://in.linkedin.com/in/sarthakahuja
google:			  https://plus.google.com/u/0/+SarthakAhuja9/posts
mail:			    sarthakahuja@outlook.com
instagram:    https://www.instagram.com/thecoldviews/

author:
  name:           'Sarthak Ahuja'
  url:            https://sarthakahuja.org

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/FrozenInk/soberCV
  site:			      http://design.sarthakahuja.org/
  mine:           https://github.com/thecoldviews
